language: node_js
node_js:
  - "12"
  - "14"
services:
  - redis
script:
  - echo 'Starting'
  - npm install
  - echo 'Testing'
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: bxcIPD6HiOmmuZjdtiujtR8C7Owpp3m1ktUVL3JwUC9drNyTDqzQuKlFAmbrscaBXXzC/cCj5oAAyylNS6w1qOjA029W4/iiYWEYVlhXXcj2bMyg6dPoymOjrY0Cpw6hl1GyVYo/HDCofLP2FnjmUEDI6y8y6qvnIRzVoclheH0rxcDSigOkuuTiJaQQxhPg9I00c+2jTI59PGFQ4O9JXl2ltqB4trpPuw8THGM23NC1wMDJyt3qQ9gR/5LZDbXH+dFAVAZWXqI8xIfSnHCmOdquwIxav2cYVrzl9JWcRRTbAbzhtBeTljQWjZq/i/R1DLmrlSksPAw8Ujy925jxDVx1+Y4IlY5b5N3v2tYuxbT4fHGeY6bHV6W1A3TnwwEw+UrjFiBDgfHXAUNbsvgoxfiyACG31HKUe8f6jbfdtNcWEK5Dwz8bQSyTkoLZ2x16GAfrsjRw9LSI5fnbz/84zo9WKPXO7jLwicFP2qNby8aeri8tespCwF/vmAjQXiJxhMXsX9yXDPPByVFTd8t90RB2p52+Y8Wufh9NVAKmG8sRwddW8fI0uzDCUHjm9RkgQXz6ioUPXv/a8VS0L42gI9KtG3Yonf6gAbCzfDovWS62jNGM3/1JIIk/LnOL7bKPj51bCfdj4RK6NdYEAb6PanuhooFdH+enwBiGrs4DdSw=
  app: nodejtestapp
  on:
    repo: MaximeChartier/5-ci-cd
  skip_cleanup: true
